#!/bin/bash

function get_pip {
    echo "Downloading pip"
    wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | python
    curl -O https://raw.github.com/pypa/pip/master/contrib/get-pip.py
    python get-pip.py
}



dir=$(dirname $(readlink -f $0))
cd $dir

ubuntu=$(grep -i "ubuntu" /etc/*-release)

echo "Creating environment"
rm -rf env
pyvenv-3.4 env
source env/bin/activate

if [[ $ubuntu || $1 == "ubuntu" || $1 == "pip" ]];
then
    get_pip
fi

echo "Installing requirements"
env/bin/pip install -r requirements.txt

if [ -f config.py ]
then
    echo "Config already exists"
else
    cp config-example.py config.py
    echo "Created config.py, please modify"
fi

echo "done"
